library(knitr)
library(dplyr)
library(readr)
library(rvest)
library(gsubfn)
library(ggplot2)
library(reshape2)
library(shiny)
library(tidyr)
library(tidyverse)
library(readxl)
library(XML)
library(reshape2)
library(maptools)
library(sp)
library(fpp2)
library(DT)
library(rmarkdown)
library(sp)
library(digest)
library(extrafont)

#uvoz funkcij za zemljevid
source("lib/uvozi.zemljevid.r")


